name: Uploading release artifacts

on:
  release:
    types: [created]

jobs:
  build:
    if: '! github.event.pull_request.draft'
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: .

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - if: matrix.os == 'ubuntu-latest'
        name: Build server on ubuntu
        working-directory: ./src/rpcserver
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libprotobuf-dev libprotoc-dev protobuf-c-compiler
          make -C ../protos/ c_protos

          
          mkdir build
          cd build
          cmake .. -DTARGET=LINUX
          make
      - if: matrix.os == 'ubuntu-latest'
        name: Upload ubuntu server artifact
        uses: actions/upload-artifact@v3
        with:
          name: rpcserver_linux
          path: ./src/rpcserver/build/rpcserver_linux

      - if: matrix.os == 'macos-latest'
        name: Build server on macos
        working-directory: ./src/rpcserver
        run: |
          brew install protobuf protobuf-c
          make -C ../protos/ c_protos
          
          mkdir build
          cd build
          cmake .. -DTARGET=IOS
          make
          cmake .. -DTARGET=OSX
          make
      - if: matrix.os == 'macos-latest'
        name: Upload iphoneos server artifact
        uses: actions/upload-artifact@v3
        with:
          name: rpcserver_ios
          path: ./src/rpcserver/build/rpcserver_ios

      - if: matrix.os == 'macos-latest'
        name: Upload macos server artifact
        uses: actions/upload-artifact@v3
        with:
          name: rpcserver_macosx
          path: ./src/rpcserver/build/rpcserver_macosx
          
      - name: Upload server artifacts to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src/rpcserver/build/rpcserver_linux
            src/rpcserver/build/rpcserver_ios
            src/rpcserver/build/rpcserver_macosx
          token: ${{ secrets.GITHUB_TOKEN }}