name: Server application

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./src/rpcserver

    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: arm64
          - os: macos-latest
            arch: x86_64
          - os: ubuntu-latest
            arch: aarch64
          - os: ubuntu-latest
            arch: i686
          - os: ubuntu-latest
            arch: x86_64

    steps:
      - uses: actions/checkout@v3
      - name: Test make
        run: |
          make clean all
