name: Uploading release artifacts

on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: .

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - if: matrix.os == 'ubuntu-latest'
        name: Build server on ubuntu
        working-directory: ./src/rpcserver
        run: |
          make SERVER_CFLAGS=-DSAFE_READ_WRITES

      - if: matrix.os == 'ubuntu-latest'
        name: Upload ubuntu server artifact
        uses: actions/upload-artifact@v3
        with:
          name: rpcserver_ubuntu_x86_64
          path: ./src/rpcserver/rpcserver

      - if: matrix.os == 'macos-latest'
        name: Build server on macos
        working-directory: ./src/rpcserver
        run: |
          ./build_darwin.sh

      - if: matrix.os == 'macos-latest'
        name: Upload iphoneos server artifact
        uses: actions/upload-artifact@v3
        with:
          name: rpcserver_iphoneos_arm64
          path: ./src/rpcserver/rpcserver_iphoneos_arm64

      - if: matrix.os == 'macos-latest'
        name: Upload macos server artifact
        uses: actions/upload-artifact@v3
        with:
          name: rpcserver_macosx_x86_64
          path: ./src/rpcserver/rpcserver_macosx_x86_64
